Add npm-publish
nextcloud/.github pull request #14
Opened 2021-07-23 23:58 UTC by Pytal

To be dispatched to @nextcloud namespaced npm package repositories :)

2021-07-24 05:25 UTC, skjnldsv commented on workflow-templates/npm-publish.properties.json
> +  "description": "Build and publish package to npm.",
```suggestion
  "description": "Build and publish package to npm on tagged releases.",
```

2021-07-24 05:26 UTC, skjnldsv approved these changes
Small nitpick, but looks great! :rocket:

2021-07-24 09:40 UTC, skjnldsv requested changes

2021-07-24 09:40 UTC, skjnldsv commented on workflow-templates/npm-publish.yml
> +        uses: actions/checkout@v2
```suggestion
    runs-on: ubuntu-latest

    name: Build and publish to npm
    steps:
      - name: Check actor permission
        uses: skjnldsv/check-actor-permission@v2
        with:
          require: admin

      - name: Checkout
        uses: actions/checkout@v2
```

2021-07-27 02:53 UTC, Pytal commented on workflow-templates/npm-publish.properties.json
> +  "description": "Build and publish package to npm.",
Added :)

2021-07-27 02:54 UTC, Pytal commented on workflow-templates/npm-publish.yml
> +        uses: actions/checkout@v2
Thanks, changes made :)

2021-07-27 06:16 UTC, skjnldsv approved these changes

2021-07-27 06:17 UTC, merged